### ISSUE TITLE
Export format to YAML, JSON, MD

### ISSUE THREAD

**Issue by fedderw** [jmbeach/vscode-list-symbols#3]
Would be cool to export as a YAML or JSON object. Custom separators for markdown would be great, too. 

```YAML
tcc_cft_tool/transform_utils.py:
	function: dq_control
		variable: df
		function: _correct_dtypes
			variable: x
	function: dq_control
		variable: df
		function: _correct_dtypes
			variable: x
```
